version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/workflow_engine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:                 # <--- NEW: Mirror code
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    command: npm run dev:api     # <--- NEW: Run nodemon  
    depends_on:
      - mongo
      - redis
    networks:
      - workflow-net

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - MONGO_URI=mongodb://mongo:27017/workflow_engine
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:                 # <--- NEW: Mirror code
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
    # We will need a nodemon entry for worker too, but for now:
    command: npm run dev:worker  # <--- NEW: Run nodemon 
    depends_on:
      - mongo
      - redis
    networks:
      - workflow-net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - workflow-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - workflow-net

networks:
  workflow-net:
    driver: bridge

volumes:
  mongo-data: